package arcana

import (
	"fmt"
	"io"
	"sort"
	"strings"
)

// GenerateTables writes TypeScript type definitions for all tables
// based on the representation table.
func GenerateTables(w io.Writer, registry *Registry) error {
	repTable := registry.RepTable()
	tableNames := sortedKeys(repTable)

	fmt.Fprintln(w, "// Auto-generated by arcana-gen. Do not edit.")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "export interface Tables {")

	for _, table := range tableNames {
		cols := repTable[table]
		fmt.Fprintf(w, "  %s: {\n", table)

		// Determine which columns are optional (not in all graphs)
		colRequired := columnRequiredness(registry, table, cols)

		for _, col := range cols {
			optional := ""
			if !colRequired[col] {
				optional = "?"
			}
			fmt.Fprintf(w, "    %s%s: %s;\n", col, optional, inferTSType(col))
		}
		fmt.Fprintln(w, "  };")
	}

	fmt.Fprintln(w, "}")
	return nil
}

// GenerateViews writes TypeScript type definitions for all views
// with their params and refs structure.
func GenerateViews(w io.Writer, registry *Registry) error {
	keys := registry.Keys()

	fmt.Fprintln(w, "// Auto-generated by arcana-gen. Do not edit.")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "export interface Views {")

	registry.mu.RLock()
	defer registry.mu.RUnlock()

	for _, key := range keys {
		def := registry.graphs[key]
		fmt.Fprintf(w, "  %s: {\n", key)

		// Params
		fmt.Fprintln(w, "    params: {")
		if def.Params != nil {
			paramNames := make([]string, 0, len(def.Params))
			for name := range def.Params {
				paramNames = append(paramNames, name)
			}
			sort.Strings(paramNames)

			for _, name := range paramNames {
				paramDef := def.Params[name]
				optional := ""
				if !paramDef.Required {
					optional = "?"
				}
				tsType := paramTypeToTS(paramDef.Type, paramDef.AllowedVals)
				fmt.Fprintf(w, "      %s%s: %s;\n", name, optional, tsType)
			}
		}
		fmt.Fprintln(w, "    };")

		// Deps (tables this view depends on)
		fmt.Fprintln(w, "    deps: {")
		for _, dep := range def.Deps {
			fmt.Fprintf(w, "      %s: %s;\n", dep.Table, formatStringArray(dep.Columns))
		}
		fmt.Fprintln(w, "    };")

		fmt.Fprintln(w, "  };")
	}

	fmt.Fprintln(w, "}")
	return nil
}

// columnRequiredness determines which columns are required (present in ALL graphs
// that reference this table) vs optional (present in some).
func columnRequiredness(registry *Registry, table string, cols []string) map[string]bool {
	registry.mu.RLock()
	defer registry.mu.RUnlock()

	graphs := registry.byTable[table]
	if len(graphs) <= 1 {
		// If only one graph uses this table, all columns are required
		result := make(map[string]bool, len(cols))
		for _, col := range cols {
			result[col] = true
		}
		return result
	}

	// Count how many graphs include each column
	colCount := make(map[string]int, len(cols))
	for _, graph := range graphs {
		for _, dep := range graph.Deps {
			if dep.Table == table {
				for _, col := range dep.Columns {
					colCount[col]++
				}
			}
		}
	}

	result := make(map[string]bool, len(cols))
	for _, col := range cols {
		result[col] = colCount[col] == len(graphs)
	}
	return result
}

func paramTypeToTS(pt ParamType, allowedVals []string) string {
	if len(allowedVals) > 0 {
		quoted := make([]string, len(allowedVals))
		for i, v := range allowedVals {
			quoted[i] = fmt.Sprintf("%q", v)
		}
		return strings.Join(quoted, " | ")
	}

	switch pt {
	case ParamTypeString, ParamTypeUUID:
		return "string"
	case ParamTypeInt:
		return "number"
	case ParamTypeFloat:
		return "number"
	case ParamTypeBool:
		return "boolean"
	default:
		return "unknown"
	}
}

func inferTSType(colName string) string {
	switch {
	case strings.HasSuffix(colName, "_at") || colName == "created_at" || colName == "updated_at":
		return "string"
	case strings.HasSuffix(colName, "_id") || colName == "id":
		return "string"
	case colName == "total" || colName == "amount" || colName == "price" || colName == "count":
		return "number"
	case strings.HasPrefix(colName, "is_") || strings.HasPrefix(colName, "has_"):
		return "boolean"
	default:
		return "string"
	}
}

func formatStringArray(arr []string) string {
	quoted := make([]string, len(arr))
	for i, s := range arr {
		quoted[i] = fmt.Sprintf("%q", s)
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
